In [1]:
!pip install vk

Requirement already satisfied: vk in /home/aidar/jupyter_dir/jupyter_env/lib/python3.8/site-packages (2.0.2)
Requirement already satisfied: requests<3.0,>=2.8 in /home/aidar/jupyter_dir/jupyter_env/lib/python3.8/site-packages (from vk) (2.27.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/aidar/jupyter_dir/jupyter_env/lib/python3.8/site-packages (from requests<3.0,>=2.8->vk) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /home/aidar/jupyter_dir/jupyter_env/lib/python3.8/site-packages (from requests<3.0,>=2.8->vk) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/aidar/jupyter_dir/jupyter_env/lib/python3.8/site-packages (from requests<3.0,>=2.8->vk) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/aidar/jupyter_dir/jupyter_env/lib/python3.8/site-packages (from requests<3.0,>=2.8->vk) (1.26.8)
WARNING: There was an error checking the latest version of pip.

In [2]:
!pip install tdqm

Collecting tdqm
  Downloading tdqm-0.0.1.tar.gz (1.4 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tqdm in /home/aidar/jupyter_dir/jupyter_env/lib/python3.8/site-packages (from tdqm) (4.63.0)
Building wheels for collected packages: tdqm
  Building wheel for tdqm (setup.py) ... done
  Created wheel for tdqm: filename=tdqm-0.0.1-py3-none-any.whl size=1319 sha256=50a67ea422e23d1dd9f7fdc68e21643c54791b45135ee87653acb8c870af7776
  Stored in directory: /home/aidar/.cache/pip/wheels/86/cd/38/f96ed05dd8049e95d8fbeaa0587664eb001a1848979636b771
Successfully built tdqm
Installing collected packages: tdqm
Successfully installed tdqm-0.0.1
WARNING: There was an error checking the latest version of pip.

In [3]:
import vk
import csv
import pandas as pd 
import time
from tqdm import tqdm

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
# Подключение к API
if __name__ == "__main__": 
    token = "736fb541736fb541736fb5417d73130dc27736f736fb54111e5ea9c635d6aa8f20493c8"  # Сервисный ключ доступа
    session = vk.Session(access_token=token)  # Авторизация
    vk_api = vk.API(session)

##Posts

In [5]:
# Функция для получения id записей сообщества
def get_posts(group_id, offset, count):
  posts = vk_api.wall.get(owner_id=-group_id, offset=offset, count=count, extended=0, v=5.131)['items']
  return posts

In [6]:
# Функция для получения количества записей сообщества
def get_posts_count(group_id):
  return vk_api.wall.get(owner_id=-group_id, offset=0, count=1, extended=0, v=5.131)['count']

In [7]:
# Функция для получения id и текста записей сообщества, count x 100
def get_posts_n(group_id, count):

  for i in range(count):
    posts = get_posts(group_id, i * 100, 100)

  posts_id = [post['id'] if 'id' in post else None for post in posts]
  posts_owner_id = [post['owner_id'] if 'owner_id' in post else None for post in posts]
  posts_from_id = [post['from_id'] if 'from_id' in post else None for post in posts]
  posts_created_by = [post['created_by'] if 'created_by' in post else None for post in posts]
  posts_date = [post['date'] if 'date' in post else None for post in posts]
  posts_text = [post['text'] if 'text' in post else None for post in posts]
  posts_reply_post_id = [post['reply_post_id'] if 'reply_post_id' in post else None for post in posts]
  posts_reply_owner_id = [post['reply_owner_id'] if 'reply_owner_id' in post else None for post in posts]
  posts_copyright = [post['copyright'] if 'copyright' in post else None for post in posts]
  posts_likes = [post['likes'] if 'likes' in post else None for post in posts]
  posts_reposts = [post['reposts'] if 'reposts' in post else None for post in posts]
  posts_post_type = [post['post_type'] if 'post_type' in post else None for post in posts]
  posts_attachments = [post['attachments'] if 'attachments' in post else None for post in posts]
  posts_copy_history = [post['copy_history'] if 'copy_history' in post else None for post in posts]
  posts_comments = [post['comments'] if 'comments' in post else None for post in posts]


  return pd.DataFrame(data={'id': posts_id,
                            'owner_id': posts_owner_id,
                            'from_id': posts_from_id,
                            'created_by': posts_created_by,
                            'date': posts_date,
                            'text': posts_text,
                            'reply_post_id': posts_reply_post_id,
                            'reply_owner_id': posts_reply_owner_id,
                            'copyright': posts_copyright,
                            'likes': posts_likes,
                            'reposts': posts_reposts,
                            'post_type': posts_post_type,
                            'attachments': posts_attachments,
                            'copy_history': posts_copy_history,
                            'comments': posts_comments
                            })

In [8]:
# Функция для получения всех id и текста записей сообщества
def get_posts_all(group_id):

  count = get_posts_count(group_id)

  iters = count // 100
  rest = count % 100

  posts = []

  for i in tqdm(range(iters)):
    posts.extend(get_posts(group_id, i * 100, 100))

  posts.extend(get_posts(group_id, iters * 100, rest))


  posts_id = [post['id'] if 'id' in post else None for post in posts]
  posts_owner_id = [post['owner_id'] if 'owner_id' in post else None for post in posts]
  posts_from_id = [post['from_id'] if 'from_id' in post else None for post in posts]
  posts_created_by = [post['created_by'] if 'created_by' in post else None for post in posts]
  posts_date = [post['date'] if 'date' in post else None for post in posts]
  posts_text = [post['text'] if 'text' in post else None for post in posts]
  posts_reply_post_id = [post['reply_post_id'] if 'reply_post_id' in post else None for post in posts]
  posts_reply_owner_id = [post['reply_owner_id'] if 'reply_owner_id' in post else None for post in posts]
  posts_copyright = [post['copyright'] if 'copyright' in post else None for post in posts]
  posts_likes = [post['likes'] if 'likes' in post else None for post in posts]
  posts_reposts = [post['reposts'] if 'reposts' in post else None for post in posts]
  posts_post_type = [post['post_type'] if 'post_type' in post else None for post in posts]
  posts_attachments = [post['attachments'] if 'attachments' in post else None for post in posts]
  posts_copy_history = [post['copy_history'] if 'copy_history' in post else None for post in posts]
  posts_comments = [post['comments'] if 'comments' in post else None for post in posts]


  return pd.DataFrame(data={'id': posts_id,
                            'owner_id': posts_owner_id,
                            'from_id': posts_from_id,
                            'created_by': posts_created_by,
                            'date': posts_date,
                            'text': posts_text,
                            'reply_post_id': posts_reply_post_id,
                            'reply_owner_id': posts_reply_owner_id,
                            'copyright': posts_copyright,
                            'likes': posts_likes,
                            'reposts': posts_reposts,
                            'post_type': posts_post_type,
                            'attachments': posts_attachments,
                            'copy_history': posts_copy_history,
                            'comments': posts_comments
                            })

In [9]:
group_id = 184225789 #топор

get_posts_count(group_id)

25592

In [12]:
posts_big_df = get_posts_all(group_id)
len(posts_big_df)

100%|█████████████████████████████████████████| 255/255 [02:09<00:00,  1.97it/s]

25592

In [13]:
posts_big_df.head()

,id,owner_id,from_id,created_by,date,text,reply_post_id,reply_owner_id,copyright,likes,reposts,post_type,attachments,copy_history,comments
0,13574528,-184225789,-184225789,None,1654601040,"Писателя Дмитрия Глуховского (""Метро 2033"", ""П...",None,None,None,"{'can_like': 1, 'count': 472, 'user_likes': 0,...","{'count': 771, 'user_reposted': 0}",post,"[{'type': 'photo', 'photo': {'album_id': -7, '...",None,"{'can_post': 1, 'count': 147}"
1,13574199,-184225789,-184225789,None,1654599120,Почти получилось тронуться,None,None,"{'id': -113482111, 'link': 'https://vk.com/wal...","{'can_like': 1, 'count': 320, 'user_likes': 0,...","{'count': 427, 'user_reposted': 0}",post,"[{'type': 'video', 'video': {'access_key': '8c...",None,"{'can_post': 1, 'count': 53}"
2,13573780,-184225789,-184225789,None,1654597200,"Если ты думаешь, что у тебя херовая работа, то...",None,None,None,"{'can_like': 1, 'count': 460, 'user_likes': 0,...","{'count': 368, 'user_reposted': 0}",post,"[{'type': 'photo', 'photo': {'album_id': -7, '...",None,"{'can_post': 1, 'count': 73}"
3,13573238,-184225789,-184225789,None,1654595280,В Индии полицейские поймали мужика и обвинили ...,None,None,None,"{'can_like': 1, 'count': 755, 'user_likes': 0,...","{'count': 833, 'user_reposted': 0}",post,"[{'type': 'photo', 'photo': {'album_id': -7, '...",None,"{'can_post': 1, 'count': 142}"
4,13572800,-184225789,-184225789,None,1654593360,"Жена Бумыча показала подписчикам, как она буди...",None,None,None,"{'can_like': 1, 'count': 413, 'user_likes': 0,...","{'count': 1125, 'user_reposted': 0}",post,"[{'type': 'photo', 'photo': {'album_id': -7, '...",None,"{'can_post': 1, 'count': 166}"

In [15]:
posts_big_df.to_parquet("/content/drive/My Drive/!IBD/project/posts_topor.parquet")

##Comments

In [14]:
# Функция для получения данных комментариев записей сообщества
def get_post_comments(group_id, post_id, offset, count):
  try:
    comments = vk_api.wall.getComments(owner_id=-group_id, post_id = post_id,
                                  offset=offset, count=count, extended=0,
                                  thread_items_count = 10, v=5.131)['items']
    return comments
  except Exception as ex:
    return []

In [15]:
# Функция для получения данных комментариев записей сообщества, count x 100
def get_post_comments_n(group_id, post_id, count):
  comments_id = []
  comments_text = []
  comments_from_id = []

  for i in range(count):
    comments = get_post_comments(group_id, post_id, i * 100, 100)
    for i in range(len(comments)):
      comments_id.append(comments[i]['id'])
      comments_text.append(comments[i]['text'])
      comments_from_id.append(comments[i]['from_id'])

  return pd.DataFrame(data={'id': comments_id,
                            'text': comments_text,
                            'from_id': comments_from_id})

In [16]:
# Функция для получения всех комментариев записи сообщества
def get_post_comments_all(group_id, post_id):

  comments_count = 0

  while comments_count == 0:
    try:
      comments_count = vk_api.wall.getComments(owner_id=-group_id, post_id = post_id,
                                               offset=0, count=1, extended=0, v=5.131)['count']
    except Exception as ex:
      time.sleep(0.5)

  iters = comments_count // 100
  rest = comments_count % 100

  comments = []

  for i in range(iters):
      comments.extend(get_post_comments(group_id, post_id, i * 100, 100))

  comments.extend(get_post_comments(group_id, post_id, iters * 100, rest))


  l2_comments = []
  for comment in comments:
    if comment['thread']['count'] > 0:
      l2_comments.extend(comment['thread']['items'])

  comments.extend(l2_comments)

  comments_date = []
  comments_from_id = []
  comments_id = []
  comments_owner_id = []
  comments_post_id = []
  comments_text = []

  for i in range(len(comments)):
    if comments[i]['from_id'] != 0: #filter deleted
      comments_date.append(comments[i]['date'] if 'date' in comments[i] else None)
      comments_from_id.append(comments[i]['from_id'] if 'from_id' in comments[i] else None)
      comments_id.append(comments[i]['id'] if 'id' in comments[i] else None)
      comments_owner_id.append(comments[i]['owner_id'] if 'owner_id' in comments[i] else None)
      comments_post_id.append(comments[i]['post_id'] if 'post_id' in comments[i] else None)
      comments_text.append(comments[i]['text'] if 'text' in comments[i] else None)

  return pd.DataFrame(data={
      'date': comments_date,
      'from_id': comments_from_id,
      'id': comments_id,
      'owner_id': comments_owner_id,
      'post_id': comments_post_id,
      'text': comments_text})

In [17]:
# Функция для получения данных всех комментариев списка записей сообщества
def get_posts_comments_all(group_id, posts_id):
  
  comment_dfs = []

  for i in tqdm(range(len(posts_id))):
    comment_dfs.append(get_post_comments_all(group_id, posts_id[i]))
    

  comments = pd.concat(comment_dfs, ignore_index=True)
      
  return comments

In [ ]:
comments_df = get_posts_comments_all(group_id, list(posts_big_df['id']))

In [ ]:
comments_df.head()

In [ ]:
comments_df.to_parquet("/content/drive/My Drive/comments_lentach.parquet")

##User Profiles

In [ ]:
# Функция для получения данных пользователей по списку ID
def get_users_profiles(user_ids):
  user_id = []
  user_first = []
  user_last = []

  users = vk_api.users.get(user_ids = user_ids, v=5.131)
  for i in range(len(users)):
      user_id.append(users[i]['id'])
      user_first.append(users[i]['first_name'])
      user_last.append(users[i]['last_name'])

  return pd.DataFrame(data={'id': user_id,
                            'first_name': user_first,
                            'last_name': user_last})

In [ ]:
users_df = get_users_profiles(idx)

users_df

##User Friends and Subscriptions

In [ ]:
# Функция для получения списка друзей и подписок пользователя
# в случае приватности - поднят флаг private
def get_user_friends_subscriptions(user_id):
  #check privacy
  try:
    prv_test = vk_api.friends.get(user_id=user_id, offset = 0,
                                  count=1, v=5.131)
    count = prv_test['count']


    #FRIENDS
    
    user_friends = vk_api.friends.get(user_id=user_id,offset = 0,
                                      count=count, v=5.131)['items']

    #SUBSCRIPTIONS

    subscr_count = vk_api.users.getSubscriptions(user_id=user_id, offset = 0,
                                                 count=1, v=5.131)['groups']
    count = subscr_count['count']

    iters = count // 200
    rest = count % 200

    user_subscriptions = []

    for i in range(iters):
      subscriptions = vk_api.users.getSubscriptions(user_id=user_id, offset = i * 200,
                                                 count=200, v=5.131)['groups']['items']
      user_subscriptions.extend(subscriptions)

    subscriptions = vk_api.users.getSubscriptions(user_id=user_id, offset = iters * 200,
                                                 count=rest, v=5.131)['groups']['items']
    user_subscriptions.extend(subscriptions)

    #RESULT

    return {'user_id': user_id, 'private': 0,
            'friends': user_friends, 'subscriptions': user_subscriptions}

  except vk.exceptions.VkAPIError as ex:
    return {'user_id': user_id, 'private': 1, 'friends': [], 'subscriptions': []}

In [ ]:
# Функция для получения списка друзей и подписок списка пользователей
# в случае приватности - поднят флаг private
def get_users_friends_subscriptions(user_ids):

  user_ids = list(set(user_id for user_id in user_ids if user_id > 0))

  user_id = []
  user_private = []
  user_friends = []
  user_subscriptions = []

  req_fields = ["blacklisted",
 "country",
 "education",
 "followers_count",
 "has_photo",
 "home_town",
 "interests",
 "has_mobile",
 "occupation",
 "religion,inspired_by",
 "langs, political",
 "verified, career",
 "deactivated",
 "is_closed"]


  user_names_data = vk_api.users.get(user_ids = user_ids, fields = req_fields, v=5.131)

  user_first_name = [user['first_name'] for user in user_names_data]
  user_last_name = [user['last_name'] for user in user_names_data]

  

  user_blacklisted = [user['blacklisted'] if 'blacklisted' in user else None for user in user_names_data]
  user_country = [user['country'] if 'country' in user else None for user in user_names_data]
  user_education = [user['education'] if 'education' in user else None for user in user_names_data]
  user_followers_count = [user['followers_count'] if 'followers_count' in user else None for user in user_names_data]
  user_has_photo = [user['has_photo'] if 'has_photo' in user else None for user in user_names_data]
  user_home_town = [user['home_town'] if 'home_town' in user else None for user in user_names_data]
  user_interests = [user['interests'] if 'interests' in user else None for user in user_names_data]
  user_has_mobile = [user['has_mobile'] if 'has_mobile' in user else None for user in user_names_data]
  user_occupation = [user['occupation'] if 'occupation' in user else None for user in user_names_data]
  user_religion = [user['religion'] if 'religion' in user else None for user in user_names_data]
  user_inspired_by = [user['inspired_by'] if 'inspired_by' in user else None for user in user_names_data]
  user_langs = [user['langs'] if 'langs' in user else None for user in user_names_data]
  user_political = [user['political'] if 'political' in user else None for user in user_names_data]
  user_verified = [user['verified'] if 'verified' in user else None for user in user_names_data]
  user_career = [user['career'] if 'career' in user else None for user in user_names_data]
  user_deactivated = [user['deactivated'] if 'deactivated' in user else None for user in user_names_data]
  user_is_closed = [user['is_closed'] if 'is_closed' in user else None for user in user_names_data]

  for i in range(len(user_ids)):
    user_friends_data = get_user_friends_subscriptions(user_ids[i])
    user_id.append(user_friends_data['user_id'])
    user_private.append(user_friends_data['private'])
    user_friends.append(user_friends_data['friends'])
    user_subscriptions.append(user_friends_data['subscriptions'])
    
  
  return pd.DataFrame(data={'id': user_id,
                            'private': user_private,
                            'friends': user_friends,
                            'subscriptions': user_subscriptions,
                            'first_name': user_first_name,
                            'last_name': user_last_name,
                            'blacklisted': user_blacklisted,
                            'country': user_country,
                            'education': user_education,
                            'followers_count': user_followers_count,
                            'has_photo': user_has_photo,
                            'home_town': user_home_town,
                            'interests': user_interests,
                            'has_mobile': user_has_mobile,
                            'occupation': user_occupation,
                            'religion': user_religion,
                            'inspired_by': user_inspired_by,
                            'langs': user_langs,
                            'political': user_political,
                            'verified': user_verified,
                            'career': user_career,
                            'deactivated': user_deactivated,
                            'is_closed': user_is_closed
                            })

In [ ]:
users_friends_df = get_users_friends_subscriptions(idx[0:100])

ДУБЛИКАТЫ ID УДАЛЯЮТСЯ!

In [ ]:
users_friends_df

,id,private,friends,subscriptions,first_name,last_name,blacklisted,country,education,followers_count,...,has_mobile,occupation,religion,inspired_by,langs,political,verified,career,deactivated,is_closed
0,328625669,0,"[14536205, 19383120, 37210939, 38971232, 40337...","[164141329, 36394497, 170898432, 29534144, 201...",Inessa,Isaeva,0,"{'id': 1, 'title': 'Russia'}",None,69.0,...,1,None,None,None,None,None,0,[],None,False
1,1210379,1,[],[],Sergey,Mashkov,0,"{'id': 1, 'title': 'Russia'}",None,NaN,...,1,"{'name': 'РПКБ', 'type': 'work'}",None,None,None,None,0,None,None,True
2,25687565,1,[],[],Nikita,Klyshnikov,0,"{'id': 1, 'title': 'Russia'}",None,81.0,...,1,None,None,None,None,None,0,[],None,False
3,3091985,0,"[155256, 215719, 270611, 294034, 353300, 42089...","[8722610, 29534144, 88397640, 101982925, 32041...",Rau,Dosymbetov,0,"{'id': 1, 'title': 'Russia'}",None,272.0,...,1,"{'id': 890, 'name': 'ДВГУПС (бывш. ХабИИЖТ)', ...",None,None,None,None,0,[],None,False
4,215982114,0,"[32018, 43231, 104061, 249853, 305454, 309856,...","[29534144, 159935417, 76835213, 73174846, 1114...",Sergey,Eryshev,0,"{'id': 1, 'title': 'Russia'}",None,638.0,...,1,None,None,None,None,None,0,[],None,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,260224483,0,"[2688401, 2772582, 3052001, 4266247, 5664772, ...","[29534144, 73629052, 120075923, 48446256, 2654...",Nik,Sokolov,0,None,None,114.0,...,1,"{'id': 56402244, 'name': 'Метропедия', 'type':...",None,None,None,None,0,"[{'country_id': 2, 'group_id': 56402244}]",None,False
78,512734700,1,[],[],Vyacheslav,Trayanovich,0,"{'id': 1, 'title': 'Russia'}",None,44.0,...,1,None,None,None,None,None,0,None,None,False
79,729251310,1,[],[],Irina,Zyryanova,0,"{'id': 1, 'title': 'Russia'}",None,NaN,...,1,"{'id': 284101, 'name': 'ТГСПА им. Менделеева (...",None,None,None,None,0,None,None,True
80,8673789,0,"[11570, 54005, 303991, 789501, 1166071, 150747...","[125004421, 174197445, 29534144, 170812458, 30...",Nastya,Kosova,0,"{'id': 1, 'title': 'Russia'}",None,226.0,...,1,"{'id': 197104114, 'name': 'Fallout Ask', 'type...",None,None,None,None,0,None,None,False
81,142801406,0,"[10044988, 10130151, 18816890, 55625907, 62600...","[39723806, 29534144, 185839670, 19977823, 1820...",Kristina,Litvinova,0,"{'id': 1, 'title': 'Russia'}",None,35.0,...,1,"{'id': 429729, 'name': 'Филиал РГГМУ', 'type':...",None,None,None,None,0,[],None,False

##User Posts

In [ ]:
#get user posts

col_names = ['id', 
'owner_id', 
'from_id', 
'created_by', 
'date, text', 
'reply_post_id', 
'reply_owner_id', 
'copyright, likes', 
'reposts, post_type', 
'attachments', 
'copy_history', 
'comments']

def get_user_posts_n(user_id, count):
  try:
    posts = get_posts_n(-user_id, count)
    return posts
  except vk.exceptions.VkAPIError as ex:
    return pd.DataFrame(columns=col_names)

def get_user_posts_all(user_id):
  try:
    posts = get_posts_all(-user_id)
    return posts
  except vk.exceptions.VkAPIError as ex:
    return pd.DataFrame(columns=col_names)

In [ ]:
get_user_posts_n(1, 1)

,id,owner_id,from_id,created_by,date,text,reply_post_id,reply_owner_id,copyright,likes,reposts,post_type,attachments,copy_history,comments
0,2442097,1,1,None,1525805964,"Иногда говорят, что Telegram был заблокирован ...",None,None,None,"{'can_like': 0, 'count': 216197, 'user_likes': 0}",{'count': 4566},post,None,None,{'count': 0}
1,2431591,1,1,None,1525352753,"Михаил Светов, организатор прошедшего митинга ...",None,None,None,"{'can_like': 0, 'count': 24112, 'user_likes': 0}",{'count': 684},post,"[{'type': 'video', 'video': {'access_key': 'b6...",None,{'count': 0}
2,2422169,1,1,None,1525187997,,None,None,None,"{'can_like': 0, 'count': 104052, 'user_likes': 0}",{'count': 1434},post,"[{'type': 'photo', 'photo': {'album_id': -7, '...",None,{'count': 0}
3,2418560,1,1,None,1525168885,"Наблюдаю, как несмотря на проливной дождь, по ...",None,None,None,"{'can_like': 0, 'count': 45768, 'user_likes': 0}",{'count': 504},post,None,None,{'count': 0}
4,2412029,1,1,None,1525107823,"Потрясающая акция в Москве. Более 12,000 челов...",None,None,None,"{'can_like': 0, 'count': 27297, 'user_likes': 0}",{'count': 864},post,"[{'type': 'video', 'video': {'access_key': 'ad...",None,{'count': 0}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,145488,1,1,None,1438626942,Есть два способа отвечать на конкуренцию. Перв...,None,None,None,"{'can_like': 0, 'count': 30980, 'user_likes': 0}",{'count': 2458},post,None,None,{'count': 0}
96,58140,1,1,None,1437521614,,None,None,None,"{'can_like': 0, 'count': 109258, 'user_likes': 0}",{'count': 2726},post,"[{'type': 'photo', 'photo': {'album_id': -7, '...",None,{'count': 0}
97,45660,1,1,None,1437395197,,None,None,None,"{'can_like': 0, 'count': 26227, 'user_likes': 0}",{'count': 372},post,None,"[{'id': 2055, 'owner_id': -36048400, 'from_id'...",{'count': 0}
98,45659,1,1,None,1437394873,"Спасибо, [club36048400|HoodGraff] 👍🏻\n\n«Дело ...",None,None,None,"{'can_like': 0, 'count': 9881, 'user_likes': 0}",{'count': 141},post,"[{'type': 'link', 'link': {'url': 'http://nevn...",None,{'count': 0}
99,45657,1,1,None,1437340309,Публикую первую фотографию через Snapster – лу...,None,None,None,"{'can_like': 0, 'count': 45900, 'user_likes': 0}",{'count': 330},post,None,None,{'count': 0}